### PR TITLE
#33 bunq response

### LINKED ISSUE #33: Response is missing response headers and pagination
# How to Reproduce
1. Make a valid listing request to bunq API via the PHP SDK
2. Make a valid get/put/post/delete request to bunq API via the PHP SDK

# What Should Happen
1. The response contains response headers and pagination
2. The response contains response headers

# What Happens
1. The response does not contain response header nor pagination
2. The response does not contain response header

# Notes
1. The structural fix would be to introduce `BunqResponse` object which, besides the response model, includes the response headers and pagination

### PR DESCRIPTION
**Pull request by dnl-blkv**
Fixes #33

### CODE REVIEW

File: example/user_example.php [hunk 1]
```diff
@@ -21,9 +21,10 @@
 // Restore tha API context
 $apiContext = ApiContext::restore(ApiContext::FILENAME_CONFIG_DEFAULT);
 
-// Retrieve the user associated with this API key.
-$user = User::listing($apiContext)[INDEX_FIRST]->getUserCompany();
-
+// Retrieve the active user.
+/** @var User[] $users */
+$users = User::listing($apiContext)->getValue();
+$user= $users[INDEX_FIRST]->getUserCompany();
```
Comment (andrederoos) [inline example/user_example.php]: space

File: src/Http/ApiClient.php [hunk 2]
```diff
@@ -120,18 +133,48 @@ public function enableEncryption()
      * @param string $uri
      * @param string[] $customHeaders
      *
-     * @return StreamInterface
+     * @return BunqResponseRaw
      */
     public function get($uri, array $customHeaders = [])
     {
+        return $this->request(self::METHOD_GET, $uri, [], $customHeaders);
```
Comment (andrederoos) [inline src/Http/ApiClient.php]: bundle the CRUD functions together?

File: src/Model/Generated/AttachmentConversationContent.php [hunk 3]
```diff
@@ -36,18 +36,20 @@ class AttachmentConversationContent extends BunqModel
      * @param int $attachmentId
      * @param string[] $customHeaders
      *
-     * @return string|StreamInterface
+     * @return BunqResponse<string>
```
Comment (andrederoos) [inline src/Model/Generated/AttachmentConversationContent.php]: not really php type ;-)

File: src/Model/Generated/AttachmentMonetaryAccount.php [hunk 4]
```diff
@@ -59,13 +60,13 @@ class AttachmentMonetaryAccount extends BunqModel
      * @param int $monetaryAccountId
      * @param string[] $customHeaders
      *
-     * @return int
+     * @return BunqResponse<int>
```
Comment (andrederoos) [inline src/Model/Generated/AttachmentMonetaryAccount.php]: same?

File: src/Model/Generated/AttachmentConversationContent.php (hunk 3 above)
Comment (andrederoos) [inline src/Model/Generated/AttachmentConversationContent.php]: is this on purpose added to the generator?

File: src/Model/Generated/AttachmentMonetaryAccount.php (hunk 4 above)
Comment (dnl-blkv) [inline src/Model/Generated/AttachmentMonetaryAccount.php]: same :)

File: example/user_example.php (hunk 1 above)
Comment (dnl-blkv) [inline example/user_example.php]: Fixed

File: src/Http/ApiClient.php (hunk 2 above)
Comment (dnl-blkv) [inline src/Http/ApiClient.php]: Fixed
