### PR TITLE
Fixes #36 on php5.6

### LINKED ISSUE #36: Error in api context script
# description
The scripts used to create an API context throw errors after inserting the API-key.
Error: 
```
"Fatal error: Cannot use isset() on the result of an expression (you can use "null !== expression" instead) in /my/project/path/vendor/bunq/sdk_php/src/Model/BunqModel.php on line 180"
```

# How to reproduce

- Run the command `"vendor/bin/bunq-install"` in the project root folder, the error will be thrown after entering the enviroment and API-key.
- Run the `"api_context_save_example.php"`.

### PR DESCRIPTION
**Pull request by OGKevin**
This should fix the error shown in #36.

However the `avatar` fatal is still present when using `/sdk_php/src/Model/Generated/MonetaryAccountBank.php` 🤔 

Tests passes on`php7.1`.

### CODE REVIEW

File: example/api_context_save_example.php [hunk 1]
```diff
@@ -15,5 +15,6 @@
 const DEVICE_DESCRIPTION = 'Server 1';
 const PERMITTED_IPS = [];
 
+date_default_timezone_set('UTC'); // When using php5.6
```
Comment (dnl-blkv) [inline example/api_context_save_example.php]: Oh btw... Are server responses indeed in UTC? Which timezone do we want to stick to in there?

Comment (OGKevin) [inline example/api_context_save_example.php]: @dnl-blkv it appears that UTC is returned. But this is not documenten on the docs 🤔.

Comment (dnl-blkv) [inline example/api_context_save_example.php]: hmm, then we probably want to set this as a default for all times the date is used... In some entry point of the SDK perhaps, or just create a date wrapper to use there %)

Comment (dnl-blkv) [inline example/api_context_save_example.php]: @OGKevin let's remove this line for now and address it as a separate issue! :)

**Comment by dnl-blkv** [comment]
@andrederoos

**Comment by andrederoos** [comment]
@OGKevin the fatal still exists in `/sdk_php/src/Model/Generated/MonetaryAccountBank.php` then how can this fix works? We need MonetaryAccountBank (or at least the ID) for quite a lot of other calls?

**Comment by OGKevin** [comment]
@andrederoos Wel the particular error in #36 is fixed with this pr, however the structure we've chosen for the SDK doesn't seem to like php 5.6. We were debating on dropping 5.6 or not but have't come to a decision yet. Based on this decision we can see what we can do with the fatal. 

/cc @dnl-blkv @qurben

**Comment by dnl-blkv** [comment]
@OGKevin What is the fatal happening here?

**Comment by OGKevin** [comment]
@dnl-blkv The avatar fatal

```
Fatal error: Cannot use bunq\Model\Generated\Object\Avatar as Avatar because the name is already in use in /sdk_php/src/Model/Generated/MonetaryAccountBank.php on line 8
```

**Comment by dnl-blkv** [comment]
@OGKevin Could you please create an issue for it? (No there are no two `Avatar`s in the same namespace, the namespaces are distinct. The problem is that one of the avatars is available without namespace specification.)

**Comment by OGKevin** [comment]
ack, #38
