### PR TITLE
Add strictly typed responses; fix GET in extended models [#52]

### LINKED ISSUE #51: User::get returns empty object?
When I try to use the `User::get` function a User object will return but its completely empty.
image

I did some further debugging and it seems like the Response body is completely empty (The status code is still 200 😟 )

Im using the Sandbox Environment and the request url I'm trying to call is `sandbox.public.api.bunq.com/v1/user/3427`

### LINKED ISSUE #52: Add strictly typed BunqResponses
## How to Reproduce
1. Write code to make a request via the SDK
2. Write a code using the response of the request from (1)

## What Should Happen
1. The `$response.getValue()` has a strict type in doc block, and the IDE auto-completion works on it

## What Happens
1. The `$response.getValue()` doesn't have a strict type in doc block and therefore IDE auto-completion doesn't work on it

### PR DESCRIPTION
**Pull request by dnl-blkv**
Fixes #51 
Fixes #52

### CODE REVIEW

File: src/Http/BunqResponse.php [hunk 1]
```diff
@@ -55,4 +55,14 @@ public function getPagination()
...
     }
+
+    /**
+     * @param BunqResponse $bunqResponse
+     *
+     * @return static
+     */
+    public static function castFromBunqResponse(BunqResponse $bunqResponse): BunqResponse
+    {
+        return new static($bunqResponse->getValue(), $bunqResponse->getHeaders(), $bunqResponse->getPagination());
```
Comment (DennisSnijder) [inline src/Http/BunqResponse.php]: According to PSR-2 standard you should make this multiline.
Also makes it a bit more readable in my opinion

```php
 return new static(
            $bunqResponse->getValue(),
            $bunqResponse->getHeaders(),
            $bunqResponse->getPagination()
        );
```

File: src/Model/BunqModel.php [hunk 2]
```diff
@@ -223,43 +221,26 @@ protected static function classFromJson($class, BunqResponseRaw $responseRaw)
...
 
     /**
      * @param BunqResponseRaw $responseRaw
+     * @param string|null $wrapper
      *
      * @return BunqResponse
      * @throws BunqException   When the result is not expected.
      */
-    protected static function fromJson(BunqResponseRaw $responseRaw)
+    protected static function fromJson(BunqResponseRaw $responseRaw, string $wrapper = null)
```
Comment (DennisSnijder) [inline src/Model/BunqModel.php]: Strictly typing the return value will make the PHPDoc unnecessary.

File: src/Model/BunqModel.php [hunk 3]
```diff
@@ -270,7 +251,7 @@ private static function determineJsonResponseValue(array $responseArray)
     protected static function processForUuid(BunqResponseRaw $responseRaw)
```
Comment (DennisSnijder) [inline src/Model/BunqModel.php]: Return type? 😄

File: src/Model/BunqResponseInstallation.php [hunk 4]
```diff
@@ -0,0 +1,17 @@
+<?php
+namespace bunq\Model;
+
+use bunq\Http\BunqResponse;
+
+/**
+ */
```
Comment (DennisSnijder) [inline src/Model/BunqResponseInstallation.php]: Unnecessary PHPDoc ?

Comment (DennisSnijder) [reply src/Model/BunqResponseInstallation.php]: Also occurs in a lot of other models within this PR

File: src/Model/BunqModel.php (hunk 3 above)
Comment (dnl-blkv) [reply src/Model/BunqModel.php]: This is [WIP]; return types are coming :P

File: src/Model/BunqModel.php (hunk 2 above)
Comment (dnl-blkv) [reply src/Model/BunqModel.php]: @DennisSnijder there are some things which, as of PHP 7.0 (and partially 7.1), can be expressed with PHPDoc, but not with the strict typing of PHP. Examples are nullable return  statements (PHP 7.1+),`throws` (not present even in PHP 7.1) or late static binding.

Therefore, for now we would like to keep it to PHPDoc for now, until PHP has full and proper support of the strict typing :).

File: src/Http/BunqResponse.php (hunk 1 above)
Comment (dnl-blkv) [reply src/Http/BunqResponse.php]: @DennisSnijder Thanks, fixed!

Comment (DennisSnijder) [reply src/Http/BunqResponse.php]: @dnl-blkv Awesome! 😄

File: src/Http/Pagination.php [hunk 5]
```diff
@@ -114,10 +114,10 @@ private static function parsePaginationBody(array $paginationResponse)
      */
     private static function updatePaginationBodyIdFieldFromResponseField(
         array &$paginationBody,
```
[the remark this answers is not in the document]
Comment (dnl-blkv) [reply src/Http/Pagination.php]: This piece of logic did not change with this PR, and it is done exactly consistent with our SDKs in all the other languages. This probably should be moved to a class later, but let us keep it for a separate issue and PR! :)

File: src/Context/ApiContext.php [hunk 6]
```diff
@@ -163,19 +169,36 @@ private function initializeSessionContext()
...
+     * @param string $fileName
+     *
+     * @return string
+     * @throws BunqException When the context couldn't be loaded from the given location.
+     */
+    private static function getContextJsonString(string $fileName): string
+    {
+        $jsonString = FileUtil::getFileContents($fileName);
+
+        if ($jsonString === false) {
```
[the remark this answers is not in the document]
Comment (dnl-blkv) [reply src/Context/ApiContext.php]: Thanks for pointing out! I added try/catch around the call to `getFileContents`, so that we can still throw a context-specific exception :).

**Comment by dnl-blkv** [comment]
@andrederoos all answered/addressed

**Comment by DennisSnijder** [comment]
Thanks! @dnl-blkv 😄
